version: "3.9"

services:
  usuarios-api:
    build:
      context: ./services/usuarios-api
      dockerfile: Dockerfile
    container_name: usuarios-api-service
    ports:
      - "8001:80"
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - FIREBASE_DB_URL=${FIREBASE_DB_URL}
      - FIREBASE_CREDENTIALS_PATH=/var/www/html/config/firebase_credentials.json
    networks:
      - microservicios

  pedidos-api:
    build:
      context: ./services/pedidos-api
      dockerfile: Dockerfile
    container_name: pedidos-api-service
    environment:
      - FIREBASE_CREDENTIALS_FILE=/app/firebase_credentials.json
      - FIREBASE_DB_URL=https://proyecto-python-bb82f-default-rtdb.firebaseio.com/
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ALGORITHM=HS256
    ports:
      - "5001:5001"
    volumes:
      - ./services/pedidos-api:/app
    networks:
      - microservicios

  reportes-api:
    build:
      context: ./services/reportes-api
      dockerfile: Dockerfile
    container_name: reportes-api-service
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - FIREBASE_PROJECT_ID=reportes-microservicio
    volumes:
      - ./services/reportes-api/config/firebase_credentials.json:/app/config/firebase_credentials.json
    ports:
      - "8080:8080"
    networks:
      - microservicios

  notificaciones-api:
    build:
      context: ./services/notificaciones
      dockerfile: Dockerfile
    container_name: notificaciones-api-service
    environment:
      - FIREBASE_CREDENTIALS_FILE=/app/config/firebase_credentials.json
      - FIREBASE_DB_URL=https://notificaciones-e9779-default-rtdb.firebaseio.com
      - JWT_SECRET=${JWT_SECRET}
      - WEBHOOK_MAX_RETRIES=3
      - WEBHOOK_TIMEOUT=5.0
    volumes:
      - ./services/notificaciones/config/firebase_credentials.json:/app/config/firebase_credentials.json
    ports:
      - "7001:7001"
    networks:
      - microservicios



networks:
  microservicios:
    driver: bridge
