server.port=8080

# URLs internas de otros microservicios (dentro de Docker)
usuarios.api.url=http://usuarios-api-service
pedidos.api.url=http://pedidos-api-service:5001

# Firebase (para guardar logs / reportes)
firebase.project-id=reportes-microservicio
firebase.credentials.path=/app/config/firebase_credentials.json

# Secreto JWT (mismo que en PHP y Python)
security.jwt.secret=${JWT_SECRET}
